# Generated by Django 5.2.1 on 2025-05-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0002_alter_applicant_efficiency_prob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
