# Generated by Django 5.2.1 on 2025-06-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0003_applicant_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='channel_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='channel_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='channel_thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='channel_total_views',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='channel_video_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='channel_avg_comments',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='channel_avg_like',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='channel_follower',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='channel_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
