# Generated by Django 5.2.1 on 2025-10-22 10:10

import influencer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0004_influencer_channel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='upi_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='influencer_upi_qr_codes/', validators=[influencer.models.validate_file]),
        ),
    ]
