# Generated by Django 5.2.1 on 2025-10-22 10:37

import influencer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0005_influencer_upi_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='upi_qr_code',
            field=models.FileField(blank=True, null=True, upload_to='influencer_upi_qr_codes/', validators=[influencer.models.validate_file]),
        ),
    ]
