# Generated by Django 5.2.1 on 2025-05-19 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_niche', models.CharField(choices=[('food', 'Food & Beverage'), ('it', 'Technology / IT'), ('fashion', 'Fashion & Apparel'), ('travel', 'Travel & Tourism'), ('fitness', 'Fitness & Health'), ('beauty', 'Beauty & Skincare'), ('lifestyle', 'Lifestyle'), ('education', 'Education & Learning'), ('finance', 'Finance & Investment'), ('gaming', 'Gaming'), ('sports', 'Sports & Outdoors'), ('automotive', 'Automotive'), ('home_decor', 'Home Decor & Furniture'), ('pets', 'Pet Products'), ('entertainment', 'Entertainment & Media'), ('eco', 'Eco-friendly / Sustainability'), ('parenting', 'Parenting & Family'), ('real_estate', 'Real Estate'), ('books', 'Books & Publishing'), ('luxury', 'Luxury Goods')], max_length=50)),
                ('wallet', models.IntegerField(blank=True, default=0, null=True)),
                ('brand_acc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auths.account')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_name', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=225)),
                ('budget', models.IntegerField(max_length=10)),
                ('max_influencer', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_brand', to='brand.brand')),
            ],
        ),
    ]
