# Generated by Django 5.2.1 on 2025-05-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
