# Generated by Django 5.2.1 on 2025-10-22 10:10

import brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='upi_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='brand_upi_qr_codes/', validators=[brand.models.validate_file]),
        ),
    ]
